# Dowloading data from public databases

```{r error=TRUE}
#Retrieve list of genes on ALL Chromosomes from ENSEMBL

library(biomaRt)
chromosome1 <- getBM(attributes =c("hgnc_symbol", "ensembl_gene_id"), filters="chromosome name", values="1", mart=ensembl_mart)
chromosome1
```

# Capturing Genes and Variants related to retinoblastoma from public database
```{r error=TRUE}
install.packages("VarfromPDB")

# Print first five retinobalstoma variants from clinvar
library(VarfromPDB)
clinvar.phenotype = extract_clinvar(keyword="retinoblastoma") 
genes.clinvar = clinvar.phenotype[[1]] 
print(dim(genes.clinvar))
variants.clinvar = clinvar.phenotype[[2]] 
print(dim(variants.clinvar))
head(print(dim(variants.clinvar))
     
# Extract the genes and variants associated to retinoblastoma from uniprot
uniprot.phenotype = extract_uniprot(keyword="retinoblastoma")
head(uniprot.phenotype)

#Extract the genes and variants related to cataract in Chinese populations from PubMed

cataract_pubmed <- extract_pubmed( query = "cataract AND gene AND mutation AND chinese NOT meta analysis", keyword="cataract", localPDB="/public/home/czf/project/rare.disease/localPDB")

head(cataract_pubmed)

#Extract the phenotypes and genes from HPO
HPO.phenotype = pheno_extract_HPO("retinoblastoma")
Head(HPO.phenotype = pheno_extract_HPO("retinoblastoma")
```


